//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWinForm.CalculatorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.sasoawsdemo.bit.ueh.edu.vn/", ConfigurationName="CalculatorService.CalculatorWslmpl")]
    public interface CalculatorWslmpl {
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://services.sasoawsdemo.bit.ueh.edu.vn/)
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sasoawsdemo.bit.ueh.edu.vn/CalculatorWslmpl/addRequest", ReplyAction="http://services.sasoawsdemo.bit.ueh.edu.vn/CalculatorWslmpl/addResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CalculatorWinForm.CalculatorService.addResponse add(CalculatorWinForm.CalculatorService.addRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sasoawsdemo.bit.ueh.edu.vn/CalculatorWslmpl/addRequest", ReplyAction="http://services.sasoawsdemo.bit.ueh.edu.vn/CalculatorWslmpl/addResponse")]
        System.Threading.Tasks.Task<CalculatorWinForm.CalculatorService.addResponse> addAsync(CalculatorWinForm.CalculatorService.addRequest request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://services.sasoawsdemo.bit.ueh.edu.vn/)
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sasoawsdemo.bit.ueh.edu.vn/CalculatorWslmpl/multiplyRequest", ReplyAction="http://services.sasoawsdemo.bit.ueh.edu.vn/CalculatorWslmpl/multiplyResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CalculatorWinForm.CalculatorService.multiplyResponse multiply(CalculatorWinForm.CalculatorService.multiplyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sasoawsdemo.bit.ueh.edu.vn/CalculatorWslmpl/multiplyRequest", ReplyAction="http://services.sasoawsdemo.bit.ueh.edu.vn/CalculatorWslmpl/multiplyResponse")]
        System.Threading.Tasks.Task<CalculatorWinForm.CalculatorService.multiplyResponse> multiplyAsync(CalculatorWinForm.CalculatorService.multiplyRequest request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://services.sasoawsdemo.bit.ueh.edu.vn/)
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sasoawsdemo.bit.ueh.edu.vn/CalculatorWslmpl/subtractRequest", ReplyAction="http://services.sasoawsdemo.bit.ueh.edu.vn/CalculatorWslmpl/subtractResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CalculatorWinForm.CalculatorService.subtractResponse subtract(CalculatorWinForm.CalculatorService.subtractRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sasoawsdemo.bit.ueh.edu.vn/CalculatorWslmpl/subtractRequest", ReplyAction="http://services.sasoawsdemo.bit.ueh.edu.vn/CalculatorWslmpl/subtractResponse")]
        System.Threading.Tasks.Task<CalculatorWinForm.CalculatorService.subtractResponse> subtractAsync(CalculatorWinForm.CalculatorService.subtractRequest request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://services.sasoawsdemo.bit.ueh.edu.vn/)
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sasoawsdemo.bit.ueh.edu.vn/CalculatorWslmpl/divideRequest", ReplyAction="http://services.sasoawsdemo.bit.ueh.edu.vn/CalculatorWslmpl/divideResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CalculatorWinForm.CalculatorService.divideResponse divide(CalculatorWinForm.CalculatorService.divideRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sasoawsdemo.bit.ueh.edu.vn/CalculatorWslmpl/divideRequest", ReplyAction="http://services.sasoawsdemo.bit.ueh.edu.vn/CalculatorWslmpl/divideResponse")]
        System.Threading.Tasks.Task<CalculatorWinForm.CalculatorService.divideResponse> divideAsync(CalculatorWinForm.CalculatorService.divideRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="add", WrapperNamespace="http://services.sasoawsdemo.bit.ueh.edu.vn/", IsWrapped=true)]
    public partial class addRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int arg1;
        
        public addRequest() {
        }
        
        public addRequest(int arg0, int arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addResponse", WrapperNamespace="http://services.sasoawsdemo.bit.ueh.edu.vn/", IsWrapped=true)]
    public partial class addResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public addResponse() {
        }
        
        public addResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multiply", WrapperNamespace="http://services.sasoawsdemo.bit.ueh.edu.vn/", IsWrapped=true)]
    public partial class multiplyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int arg1;
        
        public multiplyRequest() {
        }
        
        public multiplyRequest(int arg0, int arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multiplyResponse", WrapperNamespace="http://services.sasoawsdemo.bit.ueh.edu.vn/", IsWrapped=true)]
    public partial class multiplyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public multiplyResponse() {
        }
        
        public multiplyResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="subtract", WrapperNamespace="http://services.sasoawsdemo.bit.ueh.edu.vn/", IsWrapped=true)]
    public partial class subtractRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int arg1;
        
        public subtractRequest() {
        }
        
        public subtractRequest(int arg0, int arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="subtractResponse", WrapperNamespace="http://services.sasoawsdemo.bit.ueh.edu.vn/", IsWrapped=true)]
    public partial class subtractResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public subtractResponse() {
        }
        
        public subtractResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="divide", WrapperNamespace="http://services.sasoawsdemo.bit.ueh.edu.vn/", IsWrapped=true)]
    public partial class divideRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int arg1;
        
        public divideRequest() {
        }
        
        public divideRequest(int arg0, int arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="divideResponse", WrapperNamespace="http://services.sasoawsdemo.bit.ueh.edu.vn/", IsWrapped=true)]
    public partial class divideResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public divideResponse() {
        }
        
        public divideResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculatorWslmplChannel : CalculatorWinForm.CalculatorService.CalculatorWslmpl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorWslmplClient : System.ServiceModel.ClientBase<CalculatorWinForm.CalculatorService.CalculatorWslmpl>, CalculatorWinForm.CalculatorService.CalculatorWslmpl {
        
        public CalculatorWslmplClient() {
        }
        
        public CalculatorWslmplClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorWslmplClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorWslmplClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorWslmplClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalculatorWinForm.CalculatorService.addResponse CalculatorWinForm.CalculatorService.CalculatorWslmpl.add(CalculatorWinForm.CalculatorService.addRequest request) {
            return base.Channel.add(request);
        }
        
        public int add(int arg0, int arg1) {
            CalculatorWinForm.CalculatorService.addRequest inValue = new CalculatorWinForm.CalculatorService.addRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            CalculatorWinForm.CalculatorService.addResponse retVal = ((CalculatorWinForm.CalculatorService.CalculatorWslmpl)(this)).add(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalculatorWinForm.CalculatorService.addResponse> CalculatorWinForm.CalculatorService.CalculatorWslmpl.addAsync(CalculatorWinForm.CalculatorService.addRequest request) {
            return base.Channel.addAsync(request);
        }
        
        public System.Threading.Tasks.Task<CalculatorWinForm.CalculatorService.addResponse> addAsync(int arg0, int arg1) {
            CalculatorWinForm.CalculatorService.addRequest inValue = new CalculatorWinForm.CalculatorService.addRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((CalculatorWinForm.CalculatorService.CalculatorWslmpl)(this)).addAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalculatorWinForm.CalculatorService.multiplyResponse CalculatorWinForm.CalculatorService.CalculatorWslmpl.multiply(CalculatorWinForm.CalculatorService.multiplyRequest request) {
            return base.Channel.multiply(request);
        }
        
        public int multiply(int arg0, int arg1) {
            CalculatorWinForm.CalculatorService.multiplyRequest inValue = new CalculatorWinForm.CalculatorService.multiplyRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            CalculatorWinForm.CalculatorService.multiplyResponse retVal = ((CalculatorWinForm.CalculatorService.CalculatorWslmpl)(this)).multiply(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalculatorWinForm.CalculatorService.multiplyResponse> CalculatorWinForm.CalculatorService.CalculatorWslmpl.multiplyAsync(CalculatorWinForm.CalculatorService.multiplyRequest request) {
            return base.Channel.multiplyAsync(request);
        }
        
        public System.Threading.Tasks.Task<CalculatorWinForm.CalculatorService.multiplyResponse> multiplyAsync(int arg0, int arg1) {
            CalculatorWinForm.CalculatorService.multiplyRequest inValue = new CalculatorWinForm.CalculatorService.multiplyRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((CalculatorWinForm.CalculatorService.CalculatorWslmpl)(this)).multiplyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalculatorWinForm.CalculatorService.subtractResponse CalculatorWinForm.CalculatorService.CalculatorWslmpl.subtract(CalculatorWinForm.CalculatorService.subtractRequest request) {
            return base.Channel.subtract(request);
        }
        
        public int subtract(int arg0, int arg1) {
            CalculatorWinForm.CalculatorService.subtractRequest inValue = new CalculatorWinForm.CalculatorService.subtractRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            CalculatorWinForm.CalculatorService.subtractResponse retVal = ((CalculatorWinForm.CalculatorService.CalculatorWslmpl)(this)).subtract(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalculatorWinForm.CalculatorService.subtractResponse> CalculatorWinForm.CalculatorService.CalculatorWslmpl.subtractAsync(CalculatorWinForm.CalculatorService.subtractRequest request) {
            return base.Channel.subtractAsync(request);
        }
        
        public System.Threading.Tasks.Task<CalculatorWinForm.CalculatorService.subtractResponse> subtractAsync(int arg0, int arg1) {
            CalculatorWinForm.CalculatorService.subtractRequest inValue = new CalculatorWinForm.CalculatorService.subtractRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((CalculatorWinForm.CalculatorService.CalculatorWslmpl)(this)).subtractAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalculatorWinForm.CalculatorService.divideResponse CalculatorWinForm.CalculatorService.CalculatorWslmpl.divide(CalculatorWinForm.CalculatorService.divideRequest request) {
            return base.Channel.divide(request);
        }
        
        public double divide(int arg0, int arg1) {
            CalculatorWinForm.CalculatorService.divideRequest inValue = new CalculatorWinForm.CalculatorService.divideRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            CalculatorWinForm.CalculatorService.divideResponse retVal = ((CalculatorWinForm.CalculatorService.CalculatorWslmpl)(this)).divide(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalculatorWinForm.CalculatorService.divideResponse> CalculatorWinForm.CalculatorService.CalculatorWslmpl.divideAsync(CalculatorWinForm.CalculatorService.divideRequest request) {
            return base.Channel.divideAsync(request);
        }
        
        public System.Threading.Tasks.Task<CalculatorWinForm.CalculatorService.divideResponse> divideAsync(int arg0, int arg1) {
            CalculatorWinForm.CalculatorService.divideRequest inValue = new CalculatorWinForm.CalculatorService.divideRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((CalculatorWinForm.CalculatorService.CalculatorWslmpl)(this)).divideAsync(inValue);
        }
    }
}
